name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.10.4
    - name: Compile
      run: mill slox.compile
    - name: Run test scripts
      run: echo test*.lox | xargs -n1 mill slox.run
