name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.10.4
    - name: Compile
      run: ci/build_jar.sh
    - name: Run regression tests
      run: ci/verify_test_script_output.sh
